<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Doctor;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = [
            [
                'first_name' => 'Jean',
                'last_name' => 'Mukamana',
                'email' => 'jean.mukamana@hospital.rw',
                'phone' => '+250788123456',
                'whatsapp' => '+250788123456',
                'gender' => 'female',
                'date_of_birth' => '1985-06-15',
                'national_id' => '1199085012345678',
                'medical_license_number' => 'RMD2023001',
                'specialty' => 'General Practice',
                'qualifications' => 'MBChB, University of Rwanda',
                'hospital_clinic' => 'King Faisal Hospital',
                'province' => 'Kigali',
                'district' => 'Nyarugenge',
                'address' => 'KG 123 Ave, Kigali',
                'latitude' => -1.9536,
                'longitude' => 30.0606,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '08:00', 'end' => '17:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '17:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '17:00'],
                    'thursday' => ['start' => '08:00', 'end' => '17:00'],
                    'friday' => ['start' => '08:00', 'end' => '17:00'],
                    'saturday' => ['start' => '09:00', 'end' => '13:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '5000 RWF',
                'bio' => 'Experienced general practitioner with over 10 years of experience in primary care.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 10,
                'license_expiry' => '2025-12-31',
                'emergency_contact_name' => 'Marie Mukamana',
                'emergency_contact_phone' => '+250788987654',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Pierre',
                'last_name' => 'Niyonzima',
                'email' => 'pierre.niyonzima@hospital.rw',
                'phone' => '+250787234567',
                'whatsapp' => '+250787234567',
                'gender' => 'male',
                'date_of_birth' => '1982-03-20',
                'national_id' => '1199082012345678',
                'medical_license_number' => 'RMD2023002',
                'specialty' => 'Pediatrics',
                'qualifications' => 'MBChB, MMed Pediatrics, University of Rwanda',
                'hospital_clinic' => 'Rwanda Military Hospital',
                'province' => 'Kigali',
                'district' => 'Kicukiro',
                'address' => 'KN 45 St, Kigali',
                'latitude' => -1.9369,
                'longitude' => 30.1303,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '07:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '07:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '07:00', 'end' => '18:00'],
                    'thursday' => ['start' => '07:00', 'end' => '18:00'],
                    'friday' => ['start' => '07:00', 'end' => '18:00'],
                    'saturday' => ['start' => '08:00', 'end' => '14:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '7500 RWF',
                'bio' => 'Specialized pediatrician with expertise in child healthcare and vaccination.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French', 'Swahili']),
                'years_of_experience' => 8,
                'license_expiry' => '2025-06-30',
                'emergency_contact_name' => 'Claudine Niyonzima',
                'emergency_contact_phone' => '+250787876543',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'Uwimana',
                'email' => 'grace.uwimana@hospital.rw',
                'phone' => '+250789345678',
                'whatsapp' => '+250789345678',
                'gender' => 'female',
                'date_of_birth' => '1988-11-10',
                'national_id' => '1199088012345678',
                'medical_license_number' => 'RMD2023003',
                'specialty' => 'Obstetrics & Gynecology',
                'qualifications' => 'MBChB, MMed OBGYN, University of Rwanda',
                'hospital_clinic' => 'CHUK Kigali',
                'province' => 'Kigali',
                'district' => 'Gasabo',
                'address' => 'KG 567 Ave, Kigali',
                'latitude' => -1.9769,
                'longitude' => 30.1114,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '08:00', 'end' => '20:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '20:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '20:00'],
                    'thursday' => ['start' => '08:00', 'end' => '20:00'],
                    'friday' => ['start' => '08:00', 'end' => '20:00'],
                    'saturday' => ['start' => '09:00', 'end' => '15:00'],
                    'sunday' => ['start' => '10:00', 'end' => '14:00']
                ]),
                'consultation_fee' => '10000 RWF',
                'bio' => 'Experienced OB/GYN specialist providing comprehensive women\'s healthcare services.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 6,
                'license_expiry' => '2026-03-31',
                'emergency_contact_name' => 'Joseph Uwimana',
                'emergency_contact_phone' => '+250789765432',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Emmanuel',
                'last_name' => 'Habyarimana',
                'email' => 'emmanuel.habyarimana@hospital.rw',
                'phone' => '+250786456789',
                'whatsapp' => '+250786456789',
                'gender' => 'male',
                'date_of_birth' => '1980-07-25',
                'national_id' => '1199080012345678',
                'medical_license_number' => 'RMD2023004',
                'specialty' => 'Surgery',
                'qualifications' => 'MBChB, MMed Surgery, University of Rwanda',
                'hospital_clinic' => 'Butare University Hospital',
                'province' => 'Southern',
                'district' => 'Huye',
                'address' => 'Butare, Southern Province',
                'latitude' => -2.5574,
                'longitude' => 29.7495,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '07:30', 'end' => '17:30'],
                    'tuesday' => ['start' => '07:30', 'end' => '17:30'],
                    'wednesday' => ['start' => '07:30', 'end' => '17:30'],
                    'thursday' => ['start' => '07:30', 'end' => '17:30'],
                    'friday' => ['start' => '07:30', 'end' => '17:30'],
                    'saturday' => ['start' => '08:00', 'end' => '12:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '15000 RWF',
                'bio' => 'General surgeon with expertise in abdominal and trauma surgery.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 12,
                'license_expiry' => '2025-09-30',
                'emergency_contact_name' => 'Annie Habyarimana',
                'emergency_contact_phone' => '+250786654321',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Marie',
                'last_name' => 'Mukantwari',
                'email' => 'marie.mukantwari@hospital.rw',
                'phone' => '+250785567890',
                'whatsapp' => '+250785567890',
                'gender' => 'female',
                'date_of_birth' => '1987-09-18',
                'national_id' => '1199087012345678',
                'medical_license_number' => 'RMD2023005',
                'specialty' => 'Internal Medicine',
                'qualifications' => 'MBChB, MMed Internal Medicine, University of Rwanda',
                'hospital_clinic' => 'Ruhengeri Hospital',
                'province' => 'Northern',
                'district' => 'Musanze',
                'address' => 'Musanze, Northern Province',
                'latitude' => -1.5017,
                'longitude' => 29.6321,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '08:00', 'end' => '16:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '16:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '16:00'],
                    'thursday' => ['start' => '08:00', 'end' => '16:00'],
                    'friday' => ['start' => '08:00', 'end' => '16:00'],
                    'saturday' => ['start' => '09:00', 'end' => '13:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '8000 RWF',
                'bio' => 'Internal medicine specialist with focus on chronic disease management.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 7,
                'license_expiry' => '2025-12-15',
                'emergency_contact_name' => 'Jean Mukantwari',
                'emergency_contact_phone' => '+250785432109',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Vincent',
                'last_name' => 'Ntaganda',
                'email' => 'vincent.ntaganda@hospital.rw',
                'phone' => '+250784678901',
                'whatsapp' => '+250784678901',
                'gender' => 'male',
                'date_of_birth' => '1983-12-05',
                'national_id' => '1199083012345678',
                'medical_license_number' => 'RMD2023006',
                'specialty' => 'Cardiology',
                'qualifications' => 'MBChB, MMed Cardiology, University of Rwanda',
                'hospital_clinic' => 'Kigali University Teaching Hospital',
                'province' => 'Kigali',
                'district' => 'Nyarugenge',
                'address' => 'KG 789 Ave, Kigali',
                'latitude' => -1.9441,
                'longitude' => 30.0619,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '08:00', 'end' => '17:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '17:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '17:00'],
                    'thursday' => ['start' => '08:00', 'end' => '17:00'],
                    'friday' => ['start' => '08:00', 'end' => '17:00'],
                    'saturday' => ['start' => '09:00', 'end' => '14:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '20000 RWF',
                'bio' => 'Cardiologist specializing in heart disease diagnosis and treatment.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 9,
                'license_expiry' => '2026-01-31',
                'emergency_contact_name' => 'Claire Ntaganda',
                'emergency_contact_phone' => '+250784321098',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Annie',
                'last_name' => 'Uwizeye',
                'email' => 'annie.uwizeye@hospital.rw',
                'phone' => '+250783789012',
                'whatsapp' => '+250783789012',
                'gender' => 'female',
                'date_of_birth' => '1989-04-12',
                'national_id' => '1199089012345678',
                'medical_license_number' => 'RMD2023007',
                'specialty' => 'Pediatrics',
                'qualifications' => 'MBChB, MMed Pediatrics, Makerere University',
                'hospital_clinic' => 'Rwinkwavu Hospital',
                'province' => 'Eastern',
                'district' => 'Kayonza',
                'address' => 'Kayonza, Eastern Province',
                'latitude' => -1.8962,
                'longitude' => 30.3342,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '07:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '07:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '07:00', 'end' => '18:00'],
                    'thursday' => ['start' => '07:00', 'end' => '18:00'],
                    'friday' => ['start' => '07:00', 'end' => '18:00'],
                    'saturday' => ['start' => '08:00', 'end' => '14:00'],
                    'sunday' => null
                ]),
                'consultation_fee' => '6000 RWF',
                'bio' => 'Pediatrician with special interest in child nutrition and vaccination programs.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'Swahili']),
                'years_of_experience' => 5,
                'license_expiry' => '2025-08-31',
                'emergency_contact_name' => 'David Uwizeye',
                'emergency_contact_phone' => '+250783210987',
                'last_active_at' => now(),
            ],
            [
                'first_name' => 'Jean Claude',
                'last_name' => 'Niyitegeka',
                'email' => 'jeanclaude.niyitegeka@hospital.rw',
                'phone' => '+250782890123',
                'whatsapp' => '+250782890123',
                'gender' => 'male',
                'date_of_birth' => '1984-08-30',
                'national_id' => '1199084012345678',
                'medical_license_number' => 'RMD2023008',
                'specialty' => 'Emergency Medicine',
                'qualifications' => 'MBChB, Emergency Medicine Certificate, University of Rwanda',
                'hospital_clinic' => 'Kibuye Hospital',
                'province' => 'Western',
                'district' => 'Karongi',
                'address' => 'Karongi, Western Province',
                'latitude' => -2.0588,
                'longitude' => 29.4141,
                'status' => 'active',
                'is_available' => true,
                'working_hours' => json_encode([
                    'monday' => ['start' => '12:00', 'end' => '24:00'],
                    'tuesday' => ['start' => '12:00', 'end' => '24:00'],
                    'wednesday' => ['start' => '12:00', 'end' => '24:00'],
                    'thursday' => ['start' => '12:00', 'end' => '24:00'],
                    'friday' => ['start' => '12:00', 'end' => '24:00'],
                    'saturday' => ['start' => '12:00', 'end' => '24:00'],
                    'sunday' => ['start' => '12:00', 'end' => '24:00']
                ]),
                'consultation_fee' => '12000 RWF',
                'bio' => 'Emergency medicine specialist with extensive experience in trauma and critical care.',
                'profile_photo' => null,
                'languages_spoken' => json_encode(['Kinyarwanda', 'English', 'French']),
                'years_of_experience' => 8,
                'license_expiry' => '2025-11-30',
                'emergency_contact_name' => 'Rose Niyitegeka',
                'emergency_contact_phone' => '+250782109876',
                'last_active_at' => now(),
            ],
        ];

        foreach ($doctors as $doctor) {
            Doctor::create($doctor);
        }
    }
}
