<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Comprehensive First Aid Conditions Database
    |--------------------------------------------------------------------------
    | Complete medical first aid reference data covering all major emergency
    | scenarios worldwide. Based on WHO, Red Cross, and international standards.
    | Each condition includes: steps, do's, don'ts, severity, category.
    */

    'conditions' => [
        // CARDIAC EMERGENCIES
        [
            'id' => 'cardiac-arrest',
            'name' => 'Cardiac Arrest',
            'icon' => 'fa-heart-crack',
            'severity' => 'critical',
            'category' => 'cardiac',
            'summary' => 'Sudden loss of heart function — immediate CPR required.',
            'steps' => [
                'Call 912 immediately',
                'Check for response and breathing',
                'Begin CPR: 30 compressions to 2 breaths',
                'Push hard and fast on center of chest (at least 2 inches deep)',
                'Use AED if available — follow voice prompts',
                'Continue CPR until help arrives or AED advises to stop',
            ],
            'dos' => [
                'Start CPR immediately',
                'Use AED as soon as possible',
                'Keep compressions continuous and minimize pauses',
                'Call for help loudly',
            ],
            'donts' => [
                'Do not delay CPR to check pulse for more than 10 seconds',
                'Do not stop CPR once started unless AED analyzes or victim recovers',
                'Do not remove AED pads during analysis',
                'Do not worry about breaking ribs during compressions',
            ],
            'call912' => true,
        ],
        [
            'id' => 'heart-attack',
            'name' => 'Heart Attack',
            'icon' => 'fa-heart',
            'severity' => 'critical',
            'category' => 'cardiac',
            'summary' => 'Chest pain caused by blocked blood flow to the heart muscle.',
            'steps' => [
                'Call 912 immediately',
                'Have the person sit down and rest',
                'Give aspirin (300mg) if not allergic — chew, don\'t swallow whole',
                'Help them take prescribed medication (nitroglycerin) if available',
                'Monitor consciousness and breathing',
                'Be prepared to perform CPR if they become unresponsive',
            ],
            'dos' => [
                'Keep the person calm and still',
                'Loosen tight clothing',
                'Give aspirin if available and no allergy',
                'Monitor vital signs',
            ],
            'donts' => [
                'Do not let them walk around',
                'Do not give food or drink',
                'Do not ignore symptoms even if they improve',
                'Do not wait to see if symptoms go away',
            ],
            'call912' => true,
        ],
        [
            'id' => 'angina',
            'name' => 'Angina',
            'icon' => 'fa-heart-pulse',
            'severity' => 'urgent',
            'category' => 'cardiac',
            'summary' => 'Chest pain due to reduced blood flow to the heart.',
            'steps' => [
                'Help person rest in comfortable position',
                'Give prescribed nitroglycerin if available',
                'Call 912 if pain doesn\'t improve in 5 minutes',
                'Monitor breathing and consciousness',
                'Keep warm and calm',
            ],
            'dos' => [
                'Sit person upright',
                'Give prescribed medication',
                'Monitor symptoms',
                'Stay with person',
            ],
            'donts' => [
                'Do not let person exert themselves',
                'Do not ignore chest pain',
                'Do not give unrequested medication',
            ],
            'call912' => false,
        ],

        // NEUROLOGICAL EMERGENCIES
        [
            'id' => 'stroke',
            'name' => 'Stroke',
            'icon' => 'fa-brain',
            'severity' => 'critical',
            'category' => 'neurological',
            'summary' => 'Brain damage from interrupted blood supply — act FAST.',
            'steps' => [
                'Remember FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 912',
                'Call 912 immediately — note the time symptoms started',
                'Keep the person comfortable — lay on their side if vomiting',
                'Do NOT give any food, drink, or medication',
                'Monitor breathing and consciousness',
                'Reassure them and keep them calm until help arrives',
            ],
            'dos' => [
                'Note exact time symptoms began',
                'Keep person lying down with head slightly elevated',
                'Place on side if vomiting or unconscious',
                'Cover with blanket to maintain warmth',
            ],
            'donts' => [
                'Do not give food, water, or medication',
                'Do not wait to see if symptoms improve',
                'Do not drive them to hospital — call 912',
                'Do not leave person alone',
            ],
            'call912' => true,
        ],
        [
            'id' => 'seizure',
            'name' => 'Seizures',
            'icon' => 'fa-bolt',
            'severity' => 'urgent',
            'category' => 'neurological',
            'summary' => 'Uncontrolled electrical activity in the brain causing convulsions.',
            'steps' => [
                'Clear the area of dangerous objects',
                'Do NOT restrain the person or put anything in their mouth',
                'Protect their head with something soft',
                'Time the seizure — most last 1-3 minutes',
                'Turn them on their side once convulsions stop (recovery position)',
                'Call 912 if: seizure lasts over 5 min, person injured, pregnant, diabetic',
                'Stay with them and reassure them as they recover',
            ],
            'dos' => [
                'Time the seizure accurately',
                'Clear surrounding hazards',
                'Place on side after convulsions',
                'Protect head from injury',
                'Monitor breathing',
            ],
            'donts' => [
                'Do NOT put anything in their mouth',
                'Do NOT restrain or hold down',
                'Do NOT give food or water until fully conscious',
                'Do NOT leave person alone',
            ],
            'call912' => false,
        ],
        [
            'id' => 'epilepsy',
            'name' => 'Epilepsy Convulsion',
            'icon' => 'fa-bolt',
            'severity' => 'urgent',
            'category' => 'neurological',
            'summary' => 'Major generalized seizure in person with epilepsy.',
            'steps' => [
                'Protect from injury during seizure',
                'Time the seizure',
                'Place in recovery position after convulsions',
                'Monitor breathing and consciousness',
                'Call 912 if seizure lasts >5 minutes or injury occurs',
            ],
            'dos' => [
                'Clear area of hazards',
                'Protect head with soft object',
                'Time seizure duration',
                'Place on side after seizure',
            ],
            'donts' => [
                'Do not restrain person',
                'Do not put anything in mouth',
                'Do not give food or drink during seizure',
            ],
            'call912' => false,
        ],

        // BREATHING EMERGENCIES
        [
            'id' => 'choking',
            'name' => 'Choking',
            'icon' => 'fa-lungs',
            'severity' => 'critical',
            'category' => 'breathing',
            'summary' => 'Airway blocked — person cannot breathe, speak, or cough.',
            'steps' => [
                'Ask "Are you choking?" — if they nod, act immediately',
                'Give 5 back blows: bend forward, strike between shoulder blades',
                'Give 5 abdominal thrusts (Heimlich): fist above navel, thrust inward and upward',
                'Alternate 5 back blows and 5 thrusts until blockage clears',
                'If unconscious, lower to ground and begin CPR',
                'Call 912 if blockage does not clear',
            ],
            'dos' => [
                'Encourage coughing if they can still cough',
                'Use back blows and thrusts for adults and children over 1 year',
                'Call 912 if unable to clear the blockage',
                'Continue attempts until object expelled or person unconscious',
            ],
            'donts' => [
                'Do not use abdominal thrusts on infants under 1 year',
                'Do not slap the back while the person is upright',
                'Do not give water — it can make it worse',
                'Do not panic — act quickly and calmly',
            ],
            'call912' => false,
        ],
        [
            'id' => 'asthma-attack',
            'name' => 'Asthma Attack',
            'icon' => 'fa-wind',
            'severity' => 'urgent',
            'category' => 'breathing',
            'summary' => 'Airway narrowing causing difficulty breathing, wheezing, and coughing.',
            'steps' => [
                'Help person sit upright, leaning forward slightly',
                'Help them use reliever inhaler (2 puffs) with spacer if available',
                'Stay calm and reassure them',
                'Call 912 if no improvement after 4 puffs or condition worsens',
                'Monitor breathing and consciousness',
            ],
            'dos' => [
                'Keep person calm and upright',
                'Use spacer device with inhaler',
                'Give reliever medication as prescribed',
                'Monitor response to treatment',
            ],
            'donts' => [
                'Do not let person lie flat',
                'Do not give food or drink during attack',
                'Do not leave person alone',
                'Do not ignore worsening symptoms',
            ],
            'call912' => false,
        ],
        [
            'id' => 'drowning',
            'name' => 'Drowning',
            'icon' => 'fa-water',
            'severity' => 'critical',
            'category' => 'breathing',
            'summary' => 'Difficulty breathing after submersion in water.',
            'steps' => [
                'Get the person out of water safely',
                'Call 912',
                'Check for breathing: look at chest for rise and fall',
                'If not breathing, begin CPR immediately with 5 rescue breaths first',
                'Then continue 30 compressions : 2 breaths',
                'Remove wet clothing and keep warm with blankets',
                'Always seek hospital — secondary drowning is possible',
            ],
            'dos' => [
                'Start with rescue breaths before compressions',
                'Keep person warm after rescue',
                'Always seek medical evaluation',
                'Monitor for delayed symptoms',
            ],
            'donts' => [
                'Do not attempt rescue if you can\'t swim',
                'Do not shake the person or try to drain water',
                'Do not assume they are fine after recovery',
                'Do not ignore delayed breathing problems',
            ],
            'call912' => true,
        ],

        // WOUNDS AND BLEEDING
        [
            'id' => 'severe-bleeding',
            'name' => 'Severe Bleeding',
            'icon' => 'fa-droplet',
            'severity' => 'critical',
            'category' => 'wounds',
            'summary' => 'Heavy blood loss that won\'t stop with normal pressure.',
            'steps' => [
                'Apply firm direct pressure with a clean cloth or hands',
                'Call 912 if bleeding is severe or won\'t stop',
                'Elevate the injured limb above heart level if possible',
                'If blood soaks through, add more cloth on top (don\'t remove)',
                'Apply pressure bandage firmly over the wound',
                'For life-threatening limb bleeding, use a tourniquet 2-3 inches above wound',
                'Note the time tourniquet was applied',
                'Keep person warm and monitor for shock',
            ],
            'dos' => [
                'Apply direct pressure immediately',
                'Use gloves if available',
                'Keep person lying down and warm',
                'Write tourniquet time visibly on patient',
            ],
            'donts' => [
                'Do not remove embedded objects',
                'Do not use tourniquet unless life-threatening',
                'Do not remove first cloth — add more on top',
                'Do not give food or drink',
            ],
            'call912' => true,
        ],
        [
            'id' => 'internal-bleeding',
            'name' => 'Internal Bleeding',
            'icon' => 'fa-droplet',
            'severity' => 'critical',
            'category' => 'wounds',
            'summary' => 'Bleeding inside the body that may not be visible.',
            'steps' => [
                'Call 912 immediately',
                'Lay person flat and keep warm',
                'Do NOT give food or drink',
                'Monitor for shock symptoms',
                'Check for signs of injury',
                'Apply cold packs to injured area if identified',
            ],
            'dos' => [
                'Keep person still and calm',
                'Monitor vital signs',
                'Maintain body temperature',
                'Check for bruising or swelling',
            ],
            'donts' => [
                'Do not move person unnecessarily',
                'Do not give food or drink',
                'Do not apply heat to injured area',
                'Do not delay calling for help',
            ],
            'call912' => true,
        ],
        [
            'id' => 'stab-wound',
            'name' => 'Stab Wound',
            'icon' => 'fa-knife-kitchen',
            'severity' => 'critical',
            'category' => 'wounds',
            'summary' => 'Penetrating injury from sharp object.',
            'steps' => [
                'Call 912 immediately',
                'Do NOT remove embedded object',
                'Apply pressure around object, not on it',
                'Cover with sterile dressing',
                'Monitor for shock',
                'Keep person still and warm',
            ],
            'dos' => [
                'Control bleeding around object',
                'Immobilize injured area',
                'Monitor vital signs',
                'Keep person calm',
            ],
            'donts' => [
                'Do not remove embedded object',
                'Do not apply direct pressure on object',
                'Do not give food or drink',
                'Do not move object to check depth',
            ],
            'call912' => true,
        ],

        // BURNS
        [
            'id' => 'burns',
            'name' => 'Burns',
            'icon' => 'fa-fire',
            'severity' => 'urgent',
            'category' => 'wounds',
            'summary' => 'Damage to skin from heat, chemicals, electricity, or radiation.',
            'steps' => [
                'Cool the burn under cool running water for 20 minutes',
                'Remove jewelry and clothing near the burn (not if stuck)',
                'Cover with cling film or a clean non-stick dressing',
                'Do NOT apply ice, butter, or any home remedy',
                'For major burns: call 912, do not remove clothing stuck to burn',
                'Treat for shock: lay flat, keep warm, elevate legs if possible',
                'For chemical burns: remove contaminated clothing, flush with water for 20+ min',
            ],
            'dos' => [
                'Cool with running water for at least 20 minutes',
                'Cover with non-stick dressing or cling film',
                'Seek medical help for burns larger than a palm',
                'Remove contaminated clothing for chemical burns',
            ],
            'donts' => [
                'Do not use ice — it damages tissue further',
                'Do not pop blisters',
                'Do not apply butter, toothpaste, or creams',
                'Do not break blisters or remove dead skin',
            ],
            'call912' => false,
        ],
        [
            'id' => 'chemical-burn',
            'name' => 'Chemical Burn',
            'icon' => 'fa-flask',
            'severity' => 'critical',
            'category' => 'wounds',
            'summary' => 'Burn from contact with corrosive chemicals.',
            'steps' => [
                'Call 912 immediately for severe chemical burns',
                'Remove contaminated clothing immediately',
                'Flush with cool running water for 20+ minutes',
                'Remove jewelry before swelling starts',
                'Cover with sterile dressing',
                'Identify chemical if possible for medical staff',
            ],
            'dos' => [
                'Flush with water immediately',
                'Remove contaminated clothing',
                'Protect yourself from chemical exposure',
                'Keep chemical container for medical reference',
            ],
            'donts' => [
                'Do not apply neutralizing agents',
                'Do not use creams or ointments',
                'Do not break blisters',
                'Do not delay flushing the area',
            ],
            'call912' => true,
        ],
        [
            'id' => 'electrical-burn',
            'name' => 'Electrical Burn',
            'icon' => 'fa-bolt-lightning',
            'severity' => 'critical',
            'category' => 'wounds',
            'summary' => 'Burn from electrical current causing internal damage.',
            'steps' => [
                'Call 912 immediately',
                'Turn off power source before touching person',
                'Check for breathing and pulse',
                'Begin CPR if needed',
                'Cover burn with sterile dressing',
                'Monitor for cardiac arrhythmias',
                'Always seek hospital care — internal damage may be severe',
            ],
            'dos' => [
                'Ensure power is off before approach',
                'Monitor vital signs closely',
                'Treat for shock',
                'Cover entry and exit wounds',
            ],
            'donts' => [
                'Do not touch person until power is off',
                'Do not underestimate injury severity',
                'Do not apply ice or ointments',
                'Do not move person if neck injury suspected',
            ],
            'call912' => true,
        ],

        // MUSCULOSKELETAL INJURIES
        [
            'id' => 'fractures',
            'name' => 'Fractures & Sprains',
            'icon' => 'fa-bone',
            'severity' => 'urgent',
            'category' => 'musculoskeletal',
            'summary' => 'Broken bones or injured joints causing pain, swelling, and deformity.',
            'steps' => [
                'Keep the injured area still — do not try to realign the bone',
                'Call 912 if the fracture is open (bone visible) or deformity is severe',
                'Immobilize with a splint: pad above and below the injury',
                'Apply ice pack wrapped in cloth for 15-20 minutes to reduce swelling',
                'Elevate the injured limb if possible',
                'For open fractures: cover wound with sterile dressing',
                'Monitor for shock and keep person warm',
            ],
            'dos' => [
                'Immobilize above and below the injury',
                'Use padding between splint and skin',
                'Keep the person still and calm',
                'Apply ice to reduce swelling',
                'Elevate injured limb',
            ],
            'donts' => [
                'Do not try to realign the bone',
                'Do not move the person unless necessary',
                'Do not apply ice directly to skin',
                'Do not give food or drink if surgery may be needed',
            ],
            'call912' => false,
        ],
        [
            'id' => 'dislocation',
            'name' => 'Dislocation',
            'icon' => 'fa-bone',
            'severity' => 'urgent',
            'category' => 'musculoskeletal',
            'summary' => 'Bone end forced out of joint position.',
            'steps' => [
                'Do NOT try to pop back in place',
                'Immobilize joint in current position',
                'Apply ice to reduce swelling',
                'Seek medical attention promptly',
                'Support injured area with padding',
                'Monitor circulation to affected limb',
            ],
            'dos' => [
                'Immobilize in position found',
                'Apply ice packs',
                'Support injured area',
                'Check pulse and sensation distal to injury',
            ],
            'donts' => [
                'Do not attempt to reduce dislocation',
                'Do not force joint movement',
                'Do not apply heat',
                'Do not ignore loss of sensation or pulse',
            ],
            'call912' => false,
        ],
        [
            'id' => 'amputation',
            'name' => 'Amputation',
            'icon' => 'fa-bone',
            'severity' => 'critical',
            'category' => 'musculoskeletal',
            'summary' => 'Complete or partial loss of a body part.',
            'steps' => [
                'Call 912 immediately',
                'Control bleeding with direct pressure',
                'Apply tourniquet if bleeding uncontrollable',
                'Wrap severed part in sterile gauze',
                'Place wrapped part in plastic bag',
                'Put bag in ice water — do not let part touch ice directly',
                'Monitor for shock',
            ],
            'dos' => [
                'Control bleeding immediately',
                'Preserve severed part properly',
                'Keep person warm and calm',
                'Monitor vital signs',
            ],
            'donts' => [
                'Do not pull on remaining tissue',
                'Do not freeze severed part directly',
                'Do not give food or drink',
                'Do not delay emergency care',
            ],
            'call912' => true,
        ],

        // ALLERGIC REACTIONS
        [
            'id' => 'anaphylaxis',
            'name' => 'Anaphylaxis',
            'icon' => 'fa-syringe',
            'severity' => 'critical',
            'category' => 'allergic',
            'summary' => 'Severe allergic reaction — life-threatening without treatment.',
            'steps' => [
                'Call 912 immediately',
                'Help them use their epinephrine auto-injector (EpiPen)',
                'Inject into outer thigh — can be done through clothing',
                'If no improvement in 5 minutes, give a second dose if available',
                'Lay the person flat with legs elevated',
                'Monitor breathing — be ready for CPR if needed',
                'Stay with them until emergency help arrives',
            ],
            'dos' => [
                'Use epinephrine immediately — do not delay',
                'Lay person flat, elevate legs',
                'Be prepared to give second dose',
                'Monitor airway and breathing',
                'Keep person calm',
            ],
            'donts' => [
                'Do not delay epinephrine waiting for improvement',
                'Do not give antihistamines instead of epinephrine',
                'Do not let the person stand up or walk',
                'Do not give food or drink',
            ],
            'call912' => true,
        ],
        [
            'id' => 'allergic-reaction',
            'name' => 'Mild Allergic Reaction',
            'icon' => 'fa-syringe',
            'severity' => 'moderate',
            'category' => 'allergic',
            'summary' => 'Localized allergic response without systemic symptoms.',
            'steps' => [
                'Identify and remove allergen if possible',
                'Apply cool compress to affected area',
                'Give antihistamine if available and person can swallow',
                'Monitor for progression to anaphylaxis',
                'Seek medical attention if symptoms worsen',
            ],
            'dos' => [
                'Remove allergen source',
                'Apply cold compress',
                'Give antihistamine medication',
                'Monitor symptoms closely',
            ],
            'donts' => [
                'Do not ignore spreading symptoms',
                'Do not apply heat to rash',
                'Do not scratch affected areas',
                'Do not delay seeking help if breathing affected',
            ],
            'call912' => false,
        ],

        // ENVIRONMENTAL EMERGENCIES
        [
            'id' => 'heat-stroke',
            'name' => 'Heat Stroke',
            'icon' => 'fa-temperature-high',
            'severity' => 'critical',
            'category' => 'environmental',
            'summary' => 'Body temperature over 104°F (40°C) — a medical emergency.',
            'steps' => [
                'Call 912 immediately',
                'Move person to a cool, shaded area',
                'Remove excess clothing',
                'Cool rapidly: ice packs to neck, armpits, groin; spray with cool water; fan them',
                'Immerse in cold water if available (most effective method)',
                'Do NOT give fluids if person is confused or unconscious',
                'Monitor temperature and consciousness',
                'Continue cooling until temperature drops below 101°F (38.3°C)',
            ],
            'dos' => [
                'Cool as fast as possible — every minute counts',
                'Target areas: neck, armpits, groin, head',
                'Use cold water immersion if possible',
                'Monitor temperature continuously',
            ],
            'donts' => [
                'Do not use ice baths for elderly or very young',
                'Do not give fluids if confused or unconscious',
                'Do not delay cooling to wait for ambulance',
                'Do not use alcohol rubs',
            ],
            'call912' => true,
        ],
        [
            'id' => 'heat-exhaustion',
            'name' => 'Heat Exhaustion',
            'icon' => 'fa-temperature-high',
            'severity' => 'urgent',
            'category' => 'environmental',
            'summary' => 'Overheating with heavy sweating, weakness, and nausea.',
            'steps' => [
                'Move to cool, shaded area',
                'Lie down and elevate legs slightly',
                'Cool skin with water and fan',
                'Drink cool water or sports drinks if conscious',
                'Remove excess clothing',
                'Monitor for progression to heat stroke',
                'Seek medical attention if no improvement in 30 minutes',
            ],
            'dos' => [
                'Cool person gradually',
                'Rehydrate with cool fluids',
                'Rest in cool environment',
                'Monitor temperature and symptoms',
            ],
            'donts' => [
                'Do not give caffeinated drinks',
                'Do not ignore symptoms',
                'Do not return to activity same day',
                'Do not use ice water for cooling',
            ],
            'call912' => false,
        ],
        [
            'id' => 'hypothermia',
            'name' => 'Hypothermia',
            'icon' => 'fa-temperature-low',
            'severity' => 'critical',
            'category' => 'environmental',
            'summary' => 'Body temperature below 95°F (35°C) — requires rewarming.',
            'steps' => [
                'Call 912 for severe hypothermia',
                'Remove wet clothing',
                'Move to warm, dry location',
                'Cover with blankets (including head)',
                'Apply warm compresses to neck, chest, groin',
                'Give warm sweet drinks if conscious',
                'Monitor breathing and pulse',
                'Handle gently — cardiac arrhythmias possible',
            ],
            'dos' => [
                'Remove wet clothing',
                'Warm core body first',
                'Cover with insulating blankets',
                'Monitor vital signs',
                'Handle person gently',
            ],
            'donts' => [
                'Do not apply direct heat',
                'Do not rub extremities',
                'Do not give alcohol',
                'Do not assume person is dead — warm first',
            ],
            'call912' => true,
        ],
        [
            'id' => 'frostbite',
            'name' => 'Frostbite',
            'icon' => 'fa-temperature-low',
            'severity' => 'urgent',
            'category' => 'environmental',
            'summary' => 'Freezing of body tissues causing numbness and white skin.',
            'steps' => [
                'Get out of cold immediately',
                'Remove wet clothing',
                'Rewarm gradually with warm water (100-108°F / 38-42°C)',
                'Do not walk on frostbitten feet',
                'Protect from refreezing',
                'Take pain medication as needed',
                'Seek medical attention for severe frostbite',
            ],
            'dos' => [
                'Rewarm gradually',
                'Use warm water immersion',
                'Elevate affected area',
                'Protect from further injury',
            ],
            'donts' => [
                'Do not rub affected area',
                'Do not use direct heat',
                'Do not break blisters',
                'Do not walk on frostbitten feet',
            ],
            'call912' => false,
        ],

        // POISONING AND TOXINS
        [
            'id' => 'poisoning',
            'name' => 'Poisoning',
            'icon' => 'fa-skull-crossbones',
            'severity' => 'critical',
            'category' => 'toxic',
            'summary' => 'Exposure to toxic substances through ingestion, inhalation, or skin contact.',
            'steps' => [
                'Call poison control immediately: 1-800-222-1222',
                'Call 912 if person is unconscious, having seizures, or difficulty breathing',
                'Identify poison if possible — container, amount, time',
                'Do NOT induce vomiting unless instructed',
                'Remove contaminated clothing',
                'Flush skin or eyes with water for 15-20 minutes',
                'Monitor breathing and consciousness',
            ],
            'dos' => [
                'Identify the poison',
                'Call poison control',
                'Remove from poison source',
                'Monitor vital signs',
                'Follow medical instructions exactly',
            ],
            'donts' => [
                'Do not induce vomiting unless instructed',
                'Do not give anything by mouth',
                'Do not delay calling for help',
                'Do not ignore container warnings',
            ],
            'call912' => false,
        ],
        [
            'id' => 'drug-overdose',
            'name' => 'Drug Overdose',
            'icon' => 'fa-pills',
            'severity' => 'critical',
            'category' => 'toxic',
            'summary' => 'Excessive drug use causing life-threatening symptoms.',
            'steps' => [
                'Call 912 immediately',
                'Check breathing and consciousness',
                'Begin CPR if not breathing',
                'Place in recovery position if unconscious but breathing',
                'Collect drug containers for medical staff',
                'Monitor for seizures or cardiac arrest',
                'Do NOT induce vomiting',
            ],
            'dos' => [
                'Monitor airway and breathing',
                'Collect pill bottles/containers',
                'Keep person calm',
                'Be prepared for CPR',
            ],
            'donts' => [
                'Do not induce vomiting',
                'Do not give anything by mouth',
                'Do not accuse or judge person',
                'Do not delay emergency care',
            ],
            'call912' => true,
        ],

        // BITES AND STINGS
        [
            'id' => 'snake-bite',
            'name' => 'Snake Bite',
            'icon' => 'fa-worm',
            'severity' => 'urgent',
            'category' => 'environmental',
            'summary' => 'Venomous snake bite requires urgent medical treatment.',
            'steps' => [
                'Call 912 or go to nearest hospital immediately',
                'Keep the person still and calm — movement spreads venom faster',
                'Immobilize the bitten limb with a splint',
                'Remove rings and tight clothing near the bite',
                'Note the snake\'s appearance if safe — do NOT catch it',
                'Keep the bite at or below heart level',
                'Wash gently with water — do not scrub',
                'Monitor breathing and be ready for CPR',
            ],
            'dos' => [
                'Keep person completely still',
                'Immobilize the limb',
                'Seek hospital immediately — antivenom is the only effective treatment',
                'Note time of bite',
                'Keep bite below heart level',
            ],
            'donts' => [
                'Do NOT cut the wound or attempt to suck out venom',
                'Do NOT apply a tourniquet',
                'Do NOT apply ice or heat',
                'Do NOT give alcohol or aspirin',
                'Do NOT try to catch the snake',
            ],
            'call912' => true,
        ],
        [
            'id' => 'spider-bite',
            'name' => 'Spider Bite',
            'icon' => 'fa-spider',
            'severity' => 'moderate',
            'category' => 'environmental',
            'summary' => 'Bite from spider — severity varies by species.',
            'steps' => [
                'Clean bite area with soap and water',
                'Apply cold pack to reduce pain and swelling',
                'Elevate affected limb',
                'Take over-the-counter pain reliever if needed',
                'Seek medical attention for black widow or brown recluse bites',
                'Monitor for systemic symptoms',
            ],
            'dos' => [
                'Clean the wound',
                'Apply cold compress',
                'Elevate bitten area',
                'Monitor for allergic reaction',
            ],
            'donts' => [
                'Do not cut or suck wound',
                'Do not apply heat',
                'Do not ignore spreading redness',
                'Do not delay care for venomous species',
            ],
            'call912' => false,
        ],
        [
            'id' => 'bee-sting',
            'name' => 'Bee/Wasp Sting',
            'icon' => 'fa-bug',
            'severity' => 'moderate',
            'category' => 'environmental',
            'summary' => 'Insect sting causing pain, swelling, and possible allergic reaction.',
            'steps' => [
                'Remove stinger by scraping with credit card — do not pinch',
                'Clean area with soap and water',
                'Apply cold pack to reduce swelling',
                'Monitor for allergic reaction for 30+ minutes',
                'Take antihistamine if available',
                'Call 912 if signs of anaphylaxis develop',
            ],
            'dos' => [
                'Remove stinger quickly',
                'Apply cold compress',
                'Clean the area',
                'Monitor for allergic reaction',
            ],
            'donts' => [
                'Do not squeeze stinger',
                'Do not scratch area',
                'Do not ignore breathing difficulty',
                'Do not apply heat',
            ],
            'call912' => false,
        ],
        [
            'id' => 'jellyfish-sting',
            'name' => 'Jellyfish Sting',
            'icon' => 'fa-water',
            'severity' => 'moderate',
            'category' => 'environmental',
            'summary' => 'Marine sting causing pain and skin irritation.',
            'steps' => [
                'Get out of water immediately',
                'Rinse with vinegar for 30 seconds if available',
                'Remove tentacles with tweezers or gloved hands',
                'Soak area in hot water (110-113°F / 43-45°C) for 20-45 minutes',
                'Apply cold pack if hot water not available',
                'Seek medical attention for severe reactions',
            ],
            'dos' => [
                'Rinse with vinegar',
                'Remove tentacles carefully',
                'Use hot water immersion',
                'Monitor for allergic reaction',
            ],
            'donts' => [
                'Do not rinse with fresh water',
                'Do not rub area with sand',
                'Do not apply alcohol or ammonia',
                'Do not ignore severe pain or systemic symptoms',
            ],
            'call912' => false,
        ],

        // HEAD AND FACIAL INJURIES
        [
            'id' => 'head-injury',
            'name' => 'Head Injury',
            'icon' => 'fa-brain',
            'severity' => 'critical',
            'category' => 'neurological',
            'summary' => 'Trauma to head requiring immediate assessment.',
            'steps' => [
                'Call 912 for serious head injuries',
                'Monitor consciousness and breathing',
                'Do not move neck if spinal injury suspected',
                'Apply cold pack to swelling',
                'Check for bleeding and control it',
                'Monitor for confusion, vomiting, unequal pupils',
                'Keep person still and calm',
            ],
            'dos' => [
                'Monitor level of consciousness',
                'Control bleeding',
                'Apply cold to swelling',
                'Immobilize neck if injury suspected',
                'Monitor vital signs',
            ],
            'donts' => [
                'Do not move person if neck injury suspected',
                'Do not remove embedded objects',
                'Do not give food or drink',
                'Do not leave person alone',
            ],
            'call912' => true,
        ],
        [
            'id' => 'concussion',
            'name' => 'Concussion',
            'icon' => 'fa-brain',
            'severity' => 'urgent',
            'category' => 'neurological',
            'summary' => 'Mild traumatic brain injury causing temporary brain function disruption.',
            'steps' => [
                'Rest immediately — stop activity',
                'Apply ice pack to injury for 15-20 minutes',
                'Monitor symptoms: headache, dizziness, confusion',
                'Do not let person sleep for first few hours',
                'Seek medical attention for worsening symptoms',
                'Avoid screens, reading, and mental exertion',
            ],
            'dos' => [
                'Rest physically and mentally',
                'Apply ice to swelling',
                'Monitor symptoms closely',
                'Seek medical evaluation',
            ],
            'donts' => [
                'Do not return to activity',
                'Do not drive or operate machinery',
                'Do not ignore worsening symptoms',
                'Do not take sedating medication',
            ],
            'call912' => false,
        ],
        [
            'id' => 'eye-injury',
            'name' => 'Eye Injury',
            'icon' => 'fa-eye',
            'severity' => 'urgent',
            'category' => 'facial',
            'summary' => 'Trauma to eye requiring immediate care.',
            'steps' => [
                'Do not rub the eye',
                'Flush with clean water or saline for 15 minutes (chemical injuries)',
                'Cover eye with sterile dressing or cup',
                'Do not remove embedded objects',
                'Seek immediate medical attention',
                'Keep both eyes covered if only one injured',
            ],
            'dos' => [
                'Flush chemical injuries immediately',
                'Cover eye to prevent further damage',
                'Keep person calm and still',
                'Seek medical care promptly',
            ],
            'donts' => [
                'Do not rub the eye',
                'Do not apply pressure',
                'Do not remove embedded objects',
                'Do not use eye drops without medical advice',
            ],
            'call912' => false,
        ],
        [
            'id' => 'nosebleed',
            'name' => 'Nosebleed',
            'icon' => 'fa-droplet',
            'severity' => 'minor',
            'category' => 'facial',
            'summary' => 'Bleeding from nose, usually from front part of nasal septum.',
            'steps' => [
                'Sit upright and lean slightly forward',
                'Pinch soft part of nose firmly for 10-15 minutes',
                'Breathe through mouth',
                'Apply cold compress to bridge of nose',
                'Repeat if bleeding continues',
                'Seek medical attention if bleeding persists >20 minutes',
            ],
            'dos' => [
                'Sit upright and lean forward',
                'Pinch nose firmly',
                'Apply cold compress',
                'Breathe through mouth',
            ],
            'donts' => [
                'Do not lean head back',
                'Do not blow nose',
                'Do not pick nose',
                'Do not stuff tissue deep into nose',
            ],
            'call912' => false,
        ],

        // ABDOMINAL AND DIGESTIVE EMERGENCIES
        [
            'id' => 'abdominal-pain',
            'name' => 'Severe Abdominal Pain',
            'icon' => 'fa-stomach',
            'severity' => 'urgent',
            'category' => 'abdominal',
            'summary' => 'Intense stomach pain requiring medical evaluation.',
            'steps' => [
                'Call 912 for severe, sudden pain',
                'Have person lie down comfortably',
                'Do not give food or drink',
                'Apply warm compress to abdomen if not appendicitis suspected',
                'Monitor for fever, vomiting, rigid abdomen',
                'Note pain location and character',
                'Seek medical attention promptly',
            ],
            'dos' => [
                'Keep person comfortable',
                'Monitor symptoms',
                'Note pain characteristics',
                'Keep person NPO (nothing by mouth)',
            ],
            'donts' => [
                'Do not give food or drink',
                'Do not apply heat if appendicitis possible',
                'Do not give pain medication without medical advice',
                'Do not delay seeking care',
            ],
            'call912' => false,
        ],
        [
            'id' => 'vomiting-diarrhea',
            'name' => 'Vomiting & Diarrhea',
            'icon' => 'fa-stomach',
            'severity' => 'moderate',
            'category' => 'abdominal',
            'summary' => 'Gastrointestinal distress causing fluid loss.',
            'steps' => [
                'Rest digestive system — no food for several hours',
                'Sip clear fluids gradually',
                'Use oral rehydration solution if available',
                'Monitor for dehydration signs',
                'Seek medical care for blood in stool/vomit or high fever',
                'Introduce bland foods gradually when symptoms improve',
            ],
            'dos' => [
                'Stay hydrated with clear fluids',
                'Rest completely',
                'Use oral rehydration solutions',
                'Monitor for dehydration',
            ],
            'donts' => [
                'Do not eat solid food initially',
                'Do not drink sugary or caffeinated beverages',
                'Do not ignore signs of severe dehydration',
                'Do not take anti-diarrhea medication without medical advice',
            ],
            'call912' => false,
        ],

        // DIABETIC EMERGENCIES
        [
            'id' => 'hypoglycemia',
            'name' => 'Low Blood Sugar (Hypoglycemia)',
            'icon' => 'fa-candy-cane',
            'severity' => 'urgent',
            'category' => 'medical',
            'summary' => 'Dangerously low blood glucose requiring immediate sugar.',
            'steps' => [
                'Give 15g fast-acting sugar immediately',
                'Options: glucose tablets, juice, regular soda, honey',
                'Wait 15 minutes and recheck blood sugar if possible',
                'Repeat if still low',
                'Follow with protein/carb snack once stable',
                'Call 912 if unconscious or having seizure',
            ],
            'dos' => [
                'Give sugar immediately',
                'Monitor response',
                'Have person carry glucose tabs',
                'Follow with sustaining snack',
            ],
            'donts' => [
                'Do not give diet drinks',
                'Do not force food if unconscious',
                'Do not delay treatment',
                'Do not ignore symptoms',
            ],
            'call912' => false,
        ],
        [
            'id' => 'hyperglycemia',
            'name' => 'High Blood Sugar (Hyperglycemia)',
            'icon' => 'fa-candy-cane',
            'severity' => 'urgent',
            'category' => 'medical',
            'summary' => 'Elevated blood glucose requiring medical management.',
            'steps' => [
                'Check blood sugar if possible',
                'Drink water to stay hydrated',
                'Check for ketones if diabetic',
                'Call 912 if very high with ketones or symptoms',
                'Monitor for DKA symptoms: fruity breath, deep breathing',
                'Seek medical attention for persistent high levels',
            ],
            'dos' => [
                'Stay hydrated',
                'Monitor blood sugar',
                'Check for ketones',
                'Follow diabetes care plan',
            ],
            'donts' => [
                'Do not exercise with very high blood sugar',
                'Do not ignore symptoms',
                'Do not delay seeking care for DKA',
                'Do not take extra insulin without medical advice',
            ],
            'call912' => false,
        ],

        // PREGNANCY RELATED
        [
            'id' => 'pregnancy-emergency',
            'name' => 'Pregnancy Emergency',
            'icon' => 'fa-baby',
            'severity' => 'urgent',
            'category' => 'obstetric',
            'summary' => 'Emergency during pregnancy requiring immediate care.',
            'steps' => [
                'Call 912 immediately for concerning symptoms',
                'Have woman lie on left side',
                'Monitor vital signs and fetal movement',
                'Keep calm and reassure',
                'Time contractions if in labor',
                'Note bleeding, fluid loss, pain characteristics',
                'Prepare for possible delivery',
            ],
            'dos' => [
                'Call emergency services promptly',
                'Position on left side',
                'Monitor symptoms',
                'Stay with woman',
            ],
            'donts' => [
                'Do not give medication without medical advice',
                'Do not ignore decreased fetal movement',
                'Do not delay calling for help',
                'Do not leave woman alone',
            ],
            'call912' => true,
        ],

        // MENTAL HEALTH EMERGENCIES
        [
            'id' => 'panic-attack',
            'name' => 'Panic Attack',
            'icon' => 'fa-brain',
            'severity' => 'moderate',
            'category' => 'mental',
            'summary' => 'Sudden episode of intense fear and anxiety.',
            'steps' => [
                'Stay with person and remain calm',
                'Encourage slow, deep breathing',
                'Move to quiet, safe space',
                'Speak in reassuring, calm voice',
                'Help focus on one object or sensation',
                'Call 912 if symptoms don\'t improve or physical distress occurs',
            ],
            'dos' => [
                'Stay calm yourself',
                'Encourage breathing exercises',
                'Provide reassurance',
                'Remove from stressful situation',
            ],
            'donts' => [
                'Do not dismiss feelings',
                'Do not force conversation',
                'Do not rush person',
                'Do not make assumptions about cause',
            ],
            'call912' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Emergency Categories
    |--------------------------------------------------------------------------
    | Classification system for organizing emergency conditions
    */
    'categories' => [
        'cardiac' => [
            'label' => 'Cardiac Emergencies',
            'icon' => 'fa-heart',
            'color' => '#EF4444',
            'description' => 'Heart and circulatory system emergencies',
        ],
        'neurological' => [
            'label' => 'Neurological',
            'icon' => 'fa-brain',
            'color' => '#8B5CF6',
            'description' => 'Brain and nervous system emergencies',
        ],
        'breathing' => [
            'label' => 'Breathing',
            'icon' => 'fa-lungs',
            'color' => '#3B82F6',
            'description' => 'Airway and respiratory emergencies',
        ],
        'wounds' => [
            'label' => 'Wounds & Bleeding',
            'icon' => 'fa-droplet',
            'color' => '#EF4444',
            'description' => 'External and internal bleeding injuries',
        ],
        'musculoskeletal' => [
            'label' => 'Bones & Joints',
            'icon' => 'fa-bone',
            'color' => '#F59E0B',
            'description' => 'Fractures, sprains, and musculoskeletal injuries',
        ],
        'allergic' => [
            'label' => 'Allergic Reactions',
            'icon' => 'fa-syringe',
            'color' => '#EC4899',
            'description' => 'Allergy and immune system emergencies',
        ],
        'environmental' => [
            'label' => 'Environmental',
            'icon' => 'fa-temperature-high',
            'color' => '#10B981',
            'description' => 'Heat, cold, and environmental emergencies',
        ],
        'toxic' => [
            'label' => 'Poisoning & Overdose',
            'icon' => 'fa-skull-crossbones',
            'color' => '#6B7280',
            'description' => 'Toxic exposure and substance emergencies',
        ],
        'facial' => [
            'label' => 'Head & Face',
            'icon' => 'fa-face-dizzy',
            'color' => '#84CC16',
            'description' => 'Head, facial, and sensory organ injuries',
        ],
        'abdominal' => [
            'label' => 'Abdominal',
            'icon' => 'fa-stomach',
            'color' => '#F97316',
            'description' => 'Digestive system and abdominal emergencies',
        ],
        'medical' => [
            'label' => 'Medical Conditions',
            'icon' => 'fa-stethoscope',
            'color' => '#06B6D4',
            'description' => 'Chronic condition emergencies and metabolic issues',
        ],
        'obstetric' => [
            'label' => 'Pregnancy & Childbirth',
            'icon' => 'fa-baby',
            'color' => '#EC4899',
            'description' => 'Pregnancy-related emergencies and childbirth',
        ],
        'mental' => [
            'label' => 'Mental Health',
            'icon' => 'fa-brain',
            'color' => '#8B5CF6',
            'description' => 'Psychological and psychiatric emergencies',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Severity Levels
    |--------------------------------------------------------------------------
    | Triage classification for emergency prioritization
    */
    'severity_levels' => [
        'critical' => [
            'label' => 'Critical',
            'color' => '#DC2626',
            'description' => 'Life-threatening - immediate action required',
            'action' => 'Call 912 immediately',
            'time_frame' => 'Minutes matter',
        ],
        'urgent' => [
            'label' => 'Urgent',
            'color' => '#F97316',
            'description' => 'Serious - prompt medical attention needed',
            'action' => 'Seek medical care within 1 hour',
            'time_frame' => 'Hours',
        ],
        'moderate' => [
            'label' => 'Moderate',
            'color' => '#FCD34D',
            'description' => 'Concerning - medical evaluation recommended',
            'action' => 'See doctor today or tomorrow',
            'time_frame' => 'Days',
        ],
        'minor' => [
            'label' => 'Minor',
            'color' => '#84CC16',
            'description' => 'Less serious - self-care usually sufficient',
            'action' => 'Home care with monitoring',
            'time_frame' => 'Self-care',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | DRSABCD Protocol
    |--------------------------------------------------------------------------
    | Standard emergency action plan
    */
    'drsabcd' => [
        'D' => [
            'label' => 'Danger',
            'description' => 'Check for dangers to yourself, the patient, and others',
            'actions' => [
                'Look for traffic, fire, electricity, chemicals',
                'Make area safe before approaching',
                'Call for specialized help if needed',
            ],
        ],
        'R' => [
            'label' => 'Response',
            'description' => 'Check if patient is conscious',
            'actions' => [
                'Call their name loudly',
                'Gently shake shoulders',
                'Check for any response',
            ],
        ],
        'S' => [
            'label' => 'Send for help',
            'description' => 'Call emergency services if needed',
            'actions' => [
                'Call 912 for life-threatening emergencies',
                'Tell operator your location and situation',
                'Stay on phone until instructed',
            ],
        ],
        'A' => [
            'label' => 'Airway',
            'description' => 'Check if airway is clear',
            'actions' => [
                'Look inside mouth for obstructions',
                'Clear visible blockages',
                'Tilt head back slightly to open airway',
            ],
        ],
        'B' => [
            'label' => 'Breathing',
            'description' => 'Check if patient is breathing normally',
            'actions' => [
                'Look for chest rise and fall',
                'Listen for breathing sounds',
                'Feel for breath on your cheek',
                'Check for 10 seconds',
            ],
        ],
        'C' => [
            'label' => 'CPR',
            'description' => 'Start CPR if not breathing',
            'actions' => [
                'Begin chest compressions',
                '30 compressions to 2 breaths',
                'Push hard and fast',
                'Continue until help arrives',
            ],
        ],
        'D' => [
            'label' => 'Defibrillation',
            'description' => 'Use AED if available',
            'actions' => [
                'Turn on AED and follow prompts',
                'Apply pads as shown',
                'Ensure no one is touching patient',
                'Deliver shock if advised',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Emergency Contact Templates
    |--------------------------------------------------------------------------
    | Default emergency contacts for different regions
    */
    'emergency_contacts' => [
        'united_states' => [
            ['name' => 'Emergency Services', 'phone' => '911', 'type' => 'emergency', 'icon' => 'fa-phone-volume'],
            ['name' => 'Poison Control', 'phone' => '1-800-222-1222', 'type' => 'emergency', 'icon' => 'fa-skull-crossbones'],
            ['name' => 'Suicide Prevention', 'phone' => '988', 'type' => 'mental', 'icon' => 'fa-heart'],
        ],
        'united_kingdom' => [
            ['name' => 'Emergency Services', 'phone' => '999', 'type' => 'emergency', 'icon' => 'fa-phone-volume'],
            ['name' => 'Non-Emergency', 'phone' => '111', 'type' => 'medical', 'icon' => 'fa-hospital'],
            ['name' => 'Poison Control', 'phone' => '0345 4647', 'type' => 'emergency', 'icon' => 'fa-skull-crossbones'],
        ],
        'europe' => [
            ['name' => 'Emergency Services', 'phone' => '112', 'type' => 'emergency', 'icon' => 'fa-phone-volume'],
            ['name' => 'Poison Control', 'phone' => ' varies by country', 'type' => 'emergency', 'icon' => 'fa-skull-crossbones'],
        ],
        'australia' => [
            ['name' => 'Emergency Services', 'phone' => '000', 'type' => 'emergency', 'icon' => 'fa-phone-volume'],
            ['name' => 'Poison Information', 'phone' => '13 11 26', 'type' => 'emergency', 'icon' => 'fa-skull-crossbones'],
        ],
        'custom' => [
            ['name' => 'Emergency Services', 'phone' => '912', 'type' => 'emergency', 'icon' => 'fa-phone-volume'],
            ['name' => 'Poison Control', 'phone' => '1-800-222-1222', 'type' => 'emergency', 'icon' => 'fa-skull-crossbones'],
        ],
    ],

];
